### ISSUE TITLE
Feedback!

### ISSUE THREAD

**Issue by zocom-david-lundholm** [codeninjah/js10-vanilla-slutprojekt#1]
Bra jobbat!

* Ni ska endast ha en javascriptfil, så städa upp ert repo och plocka bort saker som inte används.
* Sökfunktionen är väldigt ineffektiv, varje knapptryckning i sökfältet skickar iväg en request, man vill minimera hur mycket nätverkstrafik. 

Ni behöver komplettera sökfunktionen. Fråga mig om ni kör fast!

**Comment by abbasmansoori** [comment]
sökfunktionen är fixad nu

**Comment by codeninjah** [comment]
Fixat!
